<?php

/**
 * BaseAnswer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                              $id                                      Type: integer, primary key
 * @property int                              $question_id                             Type: integer
 * @property int                              $user_id                                 Type: integer
 * @property string                           $body                                    Type: string
 * @property string                           $html_body                               Type: string
 * @property int                              $relevancy_up                            Type: integer
 * @property int                              $relevancy_down                          Type: integer
 * @property Question                         $Question                                
 * @property User                             $User                                    
 * @property Doctrine_Collection|Relevancy[]  $Relevancies                             
 *  
 * @method int                                getId()                                  Type: integer, primary key
 * @method int                                getQuestionId()                          Type: integer
 * @method int                                getUserId()                              Type: integer
 * @method string                             getBody()                                Type: string
 * @method string                             getHtmlBody()                            Type: string
 * @method int                                getRelevancyUp()                         Type: integer
 * @method int                                getRelevancyDown()                       Type: integer
 * @method Question                           getQuestion()                            
 * @method User                               getUser()                                
 * @method Doctrine_Collection|Relevancy[]    getRelevancies()                         
 *  
 * @method Answer                             setId(int $val)                          Type: integer, primary key
 * @method Answer                             setQuestionId(int $val)                  Type: integer
 * @method Answer                             setUserId(int $val)                      Type: integer
 * @method Answer                             setBody(string $val)                     Type: string
 * @method Answer                             setHtmlBody(string $val)                 Type: string
 * @method Answer                             setRelevancyUp(int $val)                 Type: integer
 * @method Answer                             setRelevancyDown(int $val)               Type: integer
 * @method Answer                             setQuestion(Question $val)               
 * @method Answer                             setUser(User $val)                       
 * @method Answer                             setRelevancies(Doctrine_Collection $val) 
 *  
 * @package    project_example
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnswer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ask_answer');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('html_body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('relevancy_up', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('relevancy_down', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Relevancy as Relevancies', array(
             'local' => 'id',
             'foreign' => 'answer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created_at' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'options' => 
              array(
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}