<?php

/**
 * BaseQuestionTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int          $question_id                  Type: integer
 * @property int          $user_id                      Type: integer
 * @property string       $tag                          Type: string(100)
 * @property string       $normalized_tag               Type: string(50)
 * @property Question     $Question                     
 * @property User         $User                         
 *  
 * @method int            getQuestionId()               Type: integer
 * @method int            getUserId()                   Type: integer
 * @method string         getTag()                      Type: string(100)
 * @method string         getNormalizedTag()            Type: string(50)
 * @method Question       getQuestion()                 
 * @method User           getUser()                     
 *  
 * @method QuestionTag    setQuestionId(int $val)       Type: integer
 * @method QuestionTag    setUserId(int $val)           Type: integer
 * @method QuestionTag    setTag(string $val)           Type: string(100)
 * @method QuestionTag    setNormalizedTag(string $val) Type: string(50)
 * @method QuestionTag    setQuestion(Question $val)    
 * @method QuestionTag    setUser(User $val)            
 *  
 * @package    project_example
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestionTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ask_question_tag');
        $this->hasColumn('question_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tag', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('normalized_tag', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Question', array(
             'local' => 'question_id',
             'foreign' => 'id'));

        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created_at' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'options' => 
              array(
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}