<?php

/**
 * BaseQuestion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int                                $id                                       Type: integer, primary key
 * @property int                                $user_id                                  Type: integer
 * @property string                             $title                                    Type: string(50)
 * @property string                             $stripped_title                           Type: string(50), unique
 * @property string                             $body                                     Type: string
 * @property string                             $html_body                                Type: string
 * @property int                                $interested_users                         Type: integer
 * @property User                               $User                                     
 * @property Doctrine_Collection|Answer[]       $Answers                                  
 * @property Doctrine_Collection|Interest[]     $Interests                                
 * @property Doctrine_Collection|QuestionTag[]  $QuestionTags                             
 *  
 * @method int                                  getId()                                   Type: integer, primary key
 * @method int                                  getUserId()                               Type: integer
 * @method string                               getTitle()                                Type: string(50)
 * @method string                               getStrippedTitle()                        Type: string(50), unique
 * @method string                               getBody()                                 Type: string
 * @method string                               getHtmlBody()                             Type: string
 * @method int                                  getInterestedUsers()                      Type: integer
 * @method User                                 getUser()                                 
 * @method Doctrine_Collection|Answer[]         getAnswers()                              
 * @method Doctrine_Collection|Interest[]       getInterests()                            
 * @method Doctrine_Collection|QuestionTag[]    getQuestionTags()                         
 *  
 * @method Question                             setId(int $val)                           Type: integer, primary key
 * @method Question                             setUserId(int $val)                       Type: integer
 * @method Question                             setTitle(string $val)                     Type: string(50)
 * @method Question                             setStrippedTitle(string $val)             Type: string(50), unique
 * @method Question                             setBody(string $val)                      Type: string
 * @method Question                             setHtmlBody(string $val)                  Type: string
 * @method Question                             setInterestedUsers(int $val)              Type: integer
 * @method Question                             setUser(User $val)                        
 * @method Question                             setAnswers(Doctrine_Collection $val)      
 * @method Question                             setInterests(Doctrine_Collection $val)    
 * @method Question                             setQuestionTags(Doctrine_Collection $val) 
 *  
 * @package    project_example
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuestion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ask_question');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('stripped_title', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('html_body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('interested_users', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Answer as Answers', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('Interest as Interests', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $this->hasMany('QuestionTag as QuestionTags', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created_at' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'options' => 
              array(
              ),
             ),
             'updated_at' => 
             array(
              'name' => 'updated_at',
              'type' => 'timestamp',
              'options' => 
              array(
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}