<?php

/**
 * BaseRelevancy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int        $answer_id             Type: integer
 * @property int        $user_id               Type: integer
 * @property int        $score                 Type: integer
 * @property Answer     $Answer                
 *  
 * @method int          getAnswerId()          Type: integer
 * @method int          getUserId()            Type: integer
 * @method int          getScore()             Type: integer
 * @method Answer       getAnswer()            
 *  
 * @method Relevancy    setAnswerId(int $val)  Type: integer
 * @method Relevancy    setUserId(int $val)    Type: integer
 * @method Relevancy    setScore(int $val)     Type: integer
 * @method Relevancy    setAnswer(Answer $val) 
 *  
 * @package    project_example
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRelevancy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ask_relevancy');
        $this->hasColumn('answer_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('score', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Answer', array(
             'local' => 'answer_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created_at' => 
             array(
              'name' => 'created_at',
              'type' => 'timestamp',
              'options' => 
              array(
              ),
             ),
             ));
        $this->actAs($timestampable0);
    }
}