<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Answer extends BaseAnswer
{
	public function getRelevancyUpPercent()
	{
		$total = $this->getRelevancyUp() + $this->getRelevancyDown();

		return $total ? sprintf('%.0f', $this->getRelevancyUp() * 100 / $total) : 0;
	}

	public function getRelevancyDownPercent()
	{
		$total = $this->getRelevancyUp() + $this->getRelevancyDown();

		return $total ? sprintf('%.0f', $this->getRelevancyDown() * 100 / $total) : 0;
	}
	
	public function getRelevancys()
	{
		echo $this->getRelevancyUpPercent() .' % UP '.$this->getRelevancyDownPercent() .' % DOWN';
	}

	public static function getRecentPager($page)
	{
		
		/*
		 * Pagination sfDoctrine style
		 */
		$per_page = sfConfig::get('app_pager_homepage_max');
		 
		$pager = new sfDoctrinePager('Answer', $per_page);
		$pager->getQuery()->from('Answer a, a.Question, a.User')->orderBy('a.created_at DESC');
		$pager->setPage($page);
		$pager->init();
		
		return $pager;
	}

	public function setBody($v)
	{
		$this->rawSet('body', $v);
		
		require_once('markdown.php');
		
		//strip all html tags from text
		$v = htmlentities($v, ENT_QUOTES, 'UTF-8');
		
		$this->setHtmlBody(markdown($v));
	}
}