<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Interest extends BaseInterest
{

	public function save(Doctrine_Connection $conn = null)
	{
		if ($conn === null) {
			$conn = $this->_table->getConnection();
		}
		try
		{
			$conn->beginTransaction();

			parent::save($conn);

			// update interested_users in question table
			$question = $this->getQuestion();
			$interested_users = $question->getInterestedUsers();
			$question->setInterestedUsers($interested_users + 1);
			$question->save($conn);

			$conn->commit();
			
		}
		catch (Exception $e)
		{
			$con->rollback();
			throw $e;
		}

	}


}