<?php

/**
 * InterestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InterestTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return InterestTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Interest');
    }
}