<?php

/**
 * QuestionTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuestionTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return QuestionTagTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuestionTag');
    }
}