<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Relevancy extends BaseRelevancy
{

	public function save(Doctrine_Connection $conn = null)
	{
		if ($conn === null) {
			$conn = $this->_table->getConnection();
		}
		try
		{
			$conn->beginTransaction();

			parent::save($conn);

			// update relevancy_up or relevancy_down in Answer table
			$answer = $this->getAnswer();
			if($this->getScore() == 1)
			{
				$answer->setRelevancyUp($answer->getRelevancyUp() + 1);
			}
			else
			{
				$answer->setRelevancyDown($answer->getRelevancyDown() + 1);
			}
			$answer->save();

			$conn->commit();
			
		}
		catch (Exception $e)
		{
			$con->rollback();
			throw $e;
		}

	}


}