<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class User extends BaseUser
{

	public function setPassword($password)
	{
		$salt = md5(rand(100000, 999999).$this->getNickname().$this->getEmail());
		$this->rawSet('salt', $salt);
		$this->rawSet('sha1_password',sha1($salt.$password));
	}

	public function __toString()
	{
		return $this->getFirstName().' '.$this->getLastName();
	}

	
	public function isInterestedIn($question)
	{
		$interest = new Interest();
		$interest->setQuestion($question);
		$interest->setUserId($this->getId());
		$interest->save();
	}

	public static function retrieveByNickname($nickname)
	{
		return Doctrine_Query::create()
					->from('User')
					->where('nickname = ?', $nickname)
					->execute()
					->getFirst();
	}
	
	public static function getAuthenticatedUser($login, $password)
	{
		$user = Doctrine_Query::create()
    		->from('User')
    		->where('nickname = ?', $login)
    		->execute()
    		->getFirst();

		// nickname exists?
		if ($user)
		{
			// password is OK?
			if (sha1($user->getSalt().$password) == $user->getSha1Password())
			{
				return $user;
			}
		}

		return null;
	}
}