<?php
// auto-generated by sfDoctrineAdmin
// date: 2007/12/11 20:59:09
?>
<?php

/**
 * question actions.
 *
 * @package    askeet
 * @subpackage question
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @author     Olivier Verdier <Olivier.Verdier@gmail.com>
 * @version    SVN: $Id: actions.class.php 5639 2007-10-23 14:27:18Z Eric.Fredj $
 */
class questionActions extends sfActions
{
	public function executeList ()
	{
		$this->question_pager = Question::getHomepagePager($this->getRequestParameter('page', 1));
	}

	public function executeShow ()
	{
		$stripped_title = $this->getRequestParameter('stripped_title');
			
		$this->question = Question::getQuestionFromTitle($stripped_title);

		$this->forward404Unless($this->question);
	}

	public function executeRecent()
	{
		$this->question_pager = Question::getRecentPager($this->getRequestParameter('page', 1));
	}

	public function handleErrorAdd()
	{
		return sfView::SUCCESS;
	}

	public function executeAdd()
	{
		if ($this->getRequest()->getMethod() == sfRequest::POST)
		{
			// create question
			$user = $this->getUser()->getSubscriber();

			$question = new Question();
			$question->setTitle($this->getRequestParameter('title'));
			$question->setBody($this->getRequestParameter('body'));
			$question->setUser($user);
			$question->save();

			$user->isInterestedIn($question);

			return $this->redirect('@question?stripped_title='.$question->getStrippedTitle());
		}
	}

}
